# Site settings
title: CYC Blog
SEOTitle: CYC Blog
header-img: img/home-bg-universe.jpg
email: szcyc27@g163.com
description: "Welcome to my blog!"
#keyword: "Hello"
url: "https://yechengchu.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/YechengChu/YechengChu.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "ğŸ’» MSc Computer Science student at the University of Manchester ğŸ“š"
sidebar-avatar: /img/yc_image.JPG       # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
#zhihu_username:     qiubaiying
github_username:    YechengChu
#facebook_username:  Darren Chu
#jianshu_username:   e71990ada2fd
twitter_username:   Darren_Cyc




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# è¯„è®ºç³»ç»Ÿ
# Disqusï¼ˆhttps://disqus.com/ï¼‰
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #æ˜¯å¦å¼€å¯Gitalkè¯„è®º
  clientID: b8c07d81f620be9821c1                            #ç”Ÿæˆçš„clientID
  clientSecret: 701877fbc206708eeba2b4d809a9effda03779af    #ç”Ÿæˆçš„clientSecret
  repo: yecheng.github.io    #ä»“åº“åç§°
  owner: YechengChu    #githubç”¨æˆ·å
  admin: YechengChu
  distractionFreeMode: true #æ˜¯å¦å¯ç”¨ç±»ä¼¼FBçš„é˜´å½±é®ç½©


# ç»Ÿè®¡

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
#ga_domain: qiubaiying.top               # é»˜è®¤çš„æ˜¯ auto, è¿™é‡Œæˆ‘æ˜¯è‡ªå®šä¹‰äº†çš„åŸŸåï¼Œä½ å¦‚æœæ²¡æœ‰è‡ªå·±çš„åŸŸåï¼Œéœ€è¦æ”¹æˆauto





# Featured Tags
featured-tags: false                    # æ˜¯å¦ä½¿ç”¨é¦–é¡µæ ‡ç­¾
featured-condition-size: 1              # ç›¸åŒæ ‡ç­¾æ•°é‡å¤§äºè¿™ä¸ªæ•°ï¼Œæ‰ä¼šå‡ºç°åœ¨é¦–é¡µ



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
#friends: [
#    {
#        title: "WY",
#        href: "http://zhengwuyang.com"
#    },{
#        title: "ç®€ä¹¦Â·BY",
#        href: "http://www.jianshu.com/u/e71990ada2fd"
#    },{
#        title: "Apple",
#        href: "https://apple.com"
#    },{
#        title: "Apple Developer",
#        href: "https://developer.apple.com/"
#    }
#]
